-- TEAM RIGHT JOIN

--CREATE TABLE

CREATE TABLE mystic_manuscript.RIGHTJOIN(
	ID INT PRIMARY KEY,
	"Purchase-date" DATE,
	"Date" VARCHAR,
	"Time" VARCHAR,
	"Quarter" VARCHAR,
	Qtr INT,
	"Year" INT,
	"Month" INT,
	"Date" INT,
	"Special Day" INT,
	"Online Sale Offers " INT,
	"Day" INT,
	Weekend INT,
	Morning INT,
	Afternoon INT,
	Evening INT,
	Night INT,
	Gender INT,
	Customer ID VARCHAR,
	Gender INT,
	"Product-Name" INT,
	"Item-Status" VARCHAR,
	Quantity INT,
	Currency VARCHAR,
	"Item Price" INT,
	"Shipping-Price" INT,
	"Ship-City" VARCHAR,
	"Ship-State" VARCHAR,
	"Ship-Postal-Code" INT,
	Category VARCHAR,
	Total_amount INT,
	Author VARCHAR,
	"Publication" VARCHAR,
	"Profit Percentage" INT,
	"Profit (INR)" FLOAT,
	"Cost Price" FLOAT
)