--Check for NULL
SELECT
    COUNT(*) FILTER (WHERE id IS NULL),
    COUNT(*) FILTER (WHERE purchase_date IS NULL),
    COUNT(*) FILTER (WHERE 'date' IS NULL),
    COUNT(*) FILTER (WHERE 'time' IS NULL),
    COUNT(*) FILTER (WHERE quarter IS NULL),
    COUNT(*) FILTER (WHERE qtr IS NULL),
    COUNT(*) FILTER (WHERE year IS NULL),
    COUNT(*) FILTER (WHERE month IS NULL),
    COUNT(*) FILTER (WHERE date_day IS NULL),
    COUNT(*) FILTER (WHERE special_day IS NULL),
    COUNT(*) FILTER (WHERE online_sale_offers IS NULL),
    COUNT(*) FILTER (WHERE day IS NULL),
    COUNT(*) FILTER (WHERE weekend IS NULL),
    COUNT(*) FILTER (WHERE morning IS NULL),
    COUNT(*) FILTER (WHERE afternoon IS NULL),
    COUNT(*) FILTER (WHERE evening IS NULL),
    COUNT(*) FILTER (WHERE night IS NULL),
    COUNT(*) FILTER (WHERE gender_num IS NULL),
    COUNT(*) FILTER (WHERE customer_id IS NULL),
    COUNT(*) FILTER (WHERE gender IS NULL),
    COUNT(*) FILTER (WHERE product_name IS NULL),
    COUNT(*) FILTER (WHERE item_status IS NULL),
    COUNT(*) FILTER (WHERE quantity IS NULL),
    COUNT(*) FILTER (WHERE currency IS NULL),
    COUNT(*) FILTER (WHERE item_price IS NULL),
    COUNT(*) FILTER (WHERE shipping_price IS NULL),
    COUNT(*) FILTER (WHERE ship_state IS NULL),
    COUNT(*) FILTER (WHERE ship_postal_code IS NULL),
    COUNT(*) FILTER (WHERE category IS NULL),
    COUNT(*) FILTER (WHERE total_amount IS NULL),
    COUNT(*) FILTER (WHERE author IS NULL),
    COUNT(*) FILTER (WHERE publication IS NULL),
    COUNT(*) FILTER (WHERE profit_percentage IS NULL),
    COUNT(*) FILTER (WHERE profit_inr IS NULL),
    COUNT(*) FILTER (WHERE cost_price IS NULL)
FROM mystic_manuscript.right_join;

--Check for Duplicates
SELECT id,
       purchase_date,
       date,
       time,
       quarter,
       qtr,
       YEAR,
       MONTH,
       date_day,
       special_day,
       online_sale_offers,
       DAY,
       weekend,
       morning,
       afternoon,
       evening,
       night,
       gender_num,
       customer_id,
       gender,
       product_name,
       item_status,
       quantity,
       currency,
       item_price,
       shipping_price,
       ship_city,
       ship_state,
       ship_postal_code,
       category,
       total_amount,
       author,
       PUBLICATION,
       profit_percentage,
       profit_inr,
       cost_price,
       COUNT(*) AS duplicate_count
FROM mystic_manuscript.right_join
GROUP BY id,
         purchase_date,
         date,
         time,
         quarter,
         qtr,
         YEAR,
         MONTH,
         date_day,
         special_day,
         online_sale_offers,
         DAY,
         weekend,
         morning,
         afternoon,
         evening,
         night,
         gender_num,
         customer_id,
         gender,
         product_name,
         item_status,
         quantity,
         currency,
         item_price,
         shipping_price,
         ship_city,
         ship_state,
         ship_postal_code,
         category,
         total_amount,
         author,
         PUBLICATION,
         profit_percentage,
         profit_inr,
         cost_price
HAVING COUNT(*) > 1;
